-- create a database
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities (
	id INT NOT NULL UNIQUE AUTO_INCEMENT PRIMARY KEY,
	state_id INT NOT NULL FORGEIGN KEY(id),
	name VARCHAR(256) NOT NULL
	);
